export const FETCH_TODOS = "FETCH_TODOS";
export const FETCH_ALL_TODOS = "FETCH_ALL_TODOS";
export const FETCH_ACTIVE_TODOS = "FETCH_ACTIVE_TODOS";
export const FETCH_COMPLETED_TODOS = "FETCH_COMPLETED_TODOS";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const ADD_TODO = "ADD_TODO";
